name: password_manager_app
description: "A new Flutter project."

publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.4
  hexcolor: ^3.0.1
  uuid: ^4.5.1
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  url_launcher: ^6.0.12

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
#    - assets/images/

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
